### ISSUE TITLE
words matter scan

### ISSUE THREAD

**Issue by PhilWakelin** [cicsdev/cics-event-consumer#10]
@markcocker The following lines in this repo contain the word "master" please review , and then rename the master branch to main

cics-event-consumer\docs\javamail.md line: 40 contains: master
cics-event-consumer\docs\troubleshooting.md line: 4 contains: master
cics-event-consumer\docs\troubleshooting.md line: 8 contains: master
cics-event-consumer\examples\helloWorld.xslt line: 18 contains: master
cics-event-consumer\examples\helloWorld.xslt line: 19 contains: master
cics-event-consumer\examples\helloWorld.xslt line: 21 contains: master
cics-event-consumer\examples\helloWorld.xslt line: 22 contains: master
cics-event-consumer\examples\helloWorld.xslt line: 23 contains: master
cics-event-consumer\projects\com.ibm.cics.ca1y.web\src\com\ibm\cics\ca1y\MVSWriteToOperator.java line: 193 contains: master
cics-event-consumer\projects\com.ibm.cics.ca1y.web\src\com\ibm\cics\ca1y\MVSWriteToOperator.java line: 194 contains: master
cics-event-consumer\projects\com.ibm.cics.ca1y.web\src\com\ibm\cics\ca1y\MVSWriteToOperator.java line: 196 contains: master
cics-event-consumer\projects\com.ibm.cics.ca1y.web\src\com\ibm\cics\ca1y\MVSWriteToOperator.java line: 197 contains: master
cics-event-consumer\README.md line: 27 contains: master
cics-event-consumer\README.md line: 46 contains: master
cics-event-consumer\README.md line: 56 contains: master
cics-event-consumer\README.md line: 60 contains: master
cics-event-consumer\README.md line: 64 contains: master

**Comment by markcocker** [comment]
`master` default branch renamed to `main`

**Comment by markcocker** [comment]
@PhilWakelin Please review and close if issues resolved.
