### ISSUE TITLE
CA1Y for cics 6.1 CA1Y Exception 'java.lang.IllegalAccessError: Class com/ibm/cics/ca1y/Emit....

### ISSUE THREAD

**Issue by cinluz** [cicsdev/cics-event-consumer#16]
following the instructions :https://github.com/cicsdev/cics-event-consumer/blob/main/README.md
  we are trying to import the project unfortunately explorer returns us a series of errors

Can you help me? 
thanks
Cinluz.

 
Description	Resource	Path	Location	Type
Chat cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 56	Java Problem
Chat cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 91	Java Problem
Chat cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 118	Java Problem
Chat cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 149	Java Problem
ChatManager cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 57	Java Problem
ChatManager cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 90	Java Problem
ChatManager cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 91	Java Problem
ConnectionConfiguration cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 65	Java Problem
ConnectionConfiguration cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 65	Java Problem
DateUtils cannot be resolved	CICSHTTP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 274	Java Problem
FilenameUtils cannot be resolved	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2174	Java Problem
FileUtils cannot be resolved	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2008	Java Problem
FileUtils cannot be resolved	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2023	Java Problem
Fop cannot be resolved to a type	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 88	Java Problem
FopFactory cannot be resolved	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 85	Java Problem
FopFactory cannot be resolved to a type	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 53	Java Problem
FopFactory cannot be resolved to a type	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 83	Java Problem
FopFactory cannot be resolved to a type	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 85	Java Problem
FopFactory cannot be resolved to a type	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 88	Java Problem
FOUserAgent cannot be resolved to a type	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 83	Java Problem
FTPClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2843	Java Problem
FTPClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2885	Java Problem
FTPHTTPClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2883	Java Problem
FTPReply cannot be resolved	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2953	Java Problem
FTPSClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2888	Java Problem
FTPSClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2891	Java Problem
FTPSClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2894	Java Problem
FTPSClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2900	Java Problem
FTPSClient cannot be resolved to a type	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 2902	Java Problem
IOUtils cannot be resolved	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 1953	Java Problem
IOUtils cannot be resolved	Emit.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 1976	Java Problem
IOUtils cannot be resolved	JavaHTTP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 192	Java Problem
IOUtils cannot be resolved	Util.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 286	Java Problem
Message cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 114	Java Problem
Message cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 114	Java Problem
Message cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 149	Java Problem
Message cannot be resolved to a variable	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 114	Java Problem
MessageListener cannot be resolved to a type	XMPP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 148	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 61	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 63	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 64	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 64	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 64	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 65	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 66	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 67	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 68	Java Problem
MimeConstants cannot be resolved to a variable	ConvertFOP.java	/com.ibm.cics.ca1y.web/src/com/ibm/cics/ca1y	line 69	Java Problem

**Comment by PhilWakelin** [comment]
A Maven build file has been created to facilitate building of the project.
