### ISSUE TITLE
Security alert in com.fasterxml.jackson.core:jackson-databind

### ISSUE THREAD

**Issue by PhilWakelin** [cicsdev/cics-event-consumer#7]
The following security alert has been raised for this repo
	
Known high severity security vulnerability detected in com.fasterxml.jackson.core:jackson-databind >= 2.8.0, < 2.8.11.2 defined in pom.xml. 
pom.xml update suggested: com.fasterxml.jackson.core:jackson-databind ~> 2.8.11.2. 
Always verify the validity and compatibility of suggestions with your codebase.

**Comment by markcocker** [comment]
Resolved by commit b225f09
